//
// Created by apple on 2022/8/21.
//

#ifndef LAZY_CONTROL_BACKEND_CONSTVARIABLES_H
#define LAZY_CONTROL_BACKEND_CONSTVARIABLES_H

std::string INFO_TAG = "LAZY_CONTROL_INFO:";

#endif //LAZY_CONTROL_BACKEND_CONSTVARIABLES_H
